### ISSUE TITLE
Problem with keepalive and heartbeat

### ISSUE THREAD

**Issue by erSitzt** [videlalvaro/php-amqplib#203]
Hi,

we need to use heartbeat because the firewalls in our datacenter are terminating idle connections, so i've upgraded to the master branch to use those features.

But with keepalive set to true and heartbeat set to 10 the program exits after approximately 6 seconds because ```timed_out()``` in ```StreamIO.php``` returns ```true```.
If i raise the heartbeat interval, the timeout occurs later... i think when the library tries to write the heartbeat to the socket.

This happens when i use the loop from the RabbitMQ tutorials
```
while(count($channel->callbacks)) {
    $channel->wait();
}
```

But if i use this loop :
```
while (count($channel->callbacks)) {
    try {
        $channel->wait(null, false, 1);
    } catch (\PhpAmqpLib\Exception\AMQPTimeoutException $e) {
        // Do nothing.
    } catch (\PhpAmqpLib\Exception\AMQPRuntimeException $e) {
        // Do nothing.
    }
}
```
My program runs just fine and heartbeats are send.

Is this by design and i'm misunderstanding something here ?

**Comment by erSitzt** [comment]
Sorry, forgot to report back, all ok now !!! Thanks !!!

**Comment by majidypd** [comment]
I had this problem and it takes +2 days to me to fix this issue .
finally i MADE a solution .
As you know ` $channel->wait()`  function handle two task :
first: keep alive connection by sending heartbeat to server 
second: wait until a connection exist.
but sometimes it stock on second step and cause it to didn't send heartbeat to server .
I fix this issue by using `pcntl_fork()` before ` $channel->wait()` function.
`
      $pid = pcntl_fork();
            if ($pid == -1) {
                die('could not fork'); // Or what ever you like to do
            } else if($pid) {
                // we are the child
                while(true){
                    var_dump("I'm parent");
                    $this->send_heartbeat();
                    sleep(10);
                }
            } else {
                var_dump("I'm child");
                while (count($this->channel->callbacks))
                {
                    $this->channel->wait();
                }
            }
`
and send_heartbeat function would be : 
`
// This will work on PhpAmqpLib 2.9.2
  public function send_heartbeat()
    {
        $pkt = new \PhpAmqpLib\Wire\AMQPWriter();
        $pkt->write_octet(8);
        $pkt->write_short(0);
        $pkt->write_long(0);
        $pkt->write_octet(0xCE);
        $this->connection->getIO()->write($pkt->getvalue());
    }
`
