### ISSUE TITLE
Consumer stops receiving messages

### ISSUE THREAD

**Issue by naeemmuhammad** [videlalvaro/php-amqplib#207]
We are facing the following described issue with the consumer/worker side queuing .

Issue:

We have implemented a pdf generation producer and a consumer/worker. They interact with each other via a queue.  The producer post requests/messages for generating pdfs, worker receives messages successfully and performs its task. However, if producer does not post messages for a long time( let say it posts next message after two days) the worker stops receiving messages. In the meantime if producer keeps on sending message to that queue, messages will be stored. Once worker is restarted it receives all stored messages.

Apparently the worker connection still remains intact (because worker does not terminates) but no messages are sent to the worker.

Thanks.

**Comment by girokon** [comment]
@naeemmuhammad are you solved your problem? If yes, tell how, I have same problem

**Comment by naeemmuhammad** [comment]
Hi Girokon,
Yes, the problem is solved. In-fact the newer version of php-amqplib does not terminate idle connections, therefore i would recommend you to use the latest version. 
Also, we have developed another worker in Java and found that there is no such problem.
