### ISSUE TITLE
http://www.rabbitmq.com/tutorials/tutorial-two-php.html

### ISSUE THREAD

**Issue by jiyz105** [videlalvaro/php-amqplib#225]
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolChannelException' with message 'PRECONDITION_FAILED - unknown delivery tag 1' in /home/jiyinzheng/php-amqplib-master/PhpAmqpLib/Channel/AMQPChannel.php:191
Stack trace:
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel->channel_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 /home/jiyinzheng/php-amqplib-master/PhpAmqpLib/Channel/AbstractChannel.php(170): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 /home/jiyinzheng/php-amqplib-master/PhpAmqpLib/Channel/AbstractChannel.php(362): PhpAmqpLib\Channel\AbstractChannel->dispatch('20,40', '??,PRECONDITION...', NULL)
#3 /home/jiyinzheng/rabbitmq/consume2.php(23): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 {main}
  thrown in /home/jiyinzheng/php-amqplib-master/PhpAmqpLib/Channel/AMQPChannel.php on line 191

？？？？

**Comment by videlalvaro** [comment]
>PRECONDITION_FAILED - unknown delivery tag 1

That means your code is trying to ack a message that the servers doesn't know about.
