### ISSUE TITLE
  Channel lose connection after having thrown an error : PHP Fatal error: Call to a member function send_channel_method_frame() 

### ISSUE THREAD

**Issue by hemantthorat** [videlalvaro/php-amqplib#227]
Hi ,
I'm facing above issue.
I'm using following parameter in $mgs,
$instrument(object), $ratiosFilter(array), $computeBatchId(string) .

It work fine for few job but throwing following error for some jobs,
`PHP Fatal error:  Call to a member function send_channel_method_frame() on a non-object in /var/www/prototype/Symfony/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php on line 168`

		try {
			$amqp = $this->getContainer()->get('stockopedia.rabbitmq');
			$channel = $amqp->getChannel();
			$var = $channel->queue_declare($queue, false, true, false, false);
			var_dump($var);
			$param = array("type" => "compute", "instrument" => serialize($instrument), "ratios" => $ratiosFilter, "batchId" => $computeBatchId);	
			$msg = new AMQPMessage(json_encode($param), array('delivery_mode' => 2, 'content_type' => 'application/json'));
			$channel->basic_publish($msg, '', $queue);

			$amqp->closeChannel();
			$amqp->closeConnection();
		} catch (\Exception $e) {
			$output->writeln("EXCEPTION THROWN: " . $e->getMessage());
		}

var_dump($var) Output :

		array(3) {
		  [0]=>
		  string(5) "QueueName"
		  [1]=>
		  string(1) "0"
		  [2]=>
		  string(1) "1"
		}

Above output is same for working and non-working (throwing fatal error) jobs.
I can see "connection" object gets NULL in "send_method_frame" method.
But,
what is reason behind it ?
How to debug and fix it ?

Kindly me help with it.
Thanks,
Hemant Thorat.

**Comment by valentim** [comment]
I fix this error...I was calling the "close" method of channel after calling the "basic_consume" method and before the "process_message" method.

**Comment by githoober** [comment]
I am having exactly the same issue. Calling a method on a non object produces a Fatal error without no call trace, and it's not easy to figure out what actually calls AMQPChannel::basic_pubish() after a connection has been close in this case.

Shouldn't AMQPChannel gracefully handle such null pointer operations? For example:
if (is_null($this->connection)) {
   throw new \Exception();
}

or better yet if in , 
if  (!$this->is_open) {
{
   throw new \Exception();
}

**Comment by chmielot** [comment]
+1 Having the same problem

**Comment by chmielot** [comment]
In one of my classes I was cleaning up the AMQP connection (and channel) in a destructor. Most probably it interfered with the destructor of AMQPConnection class. After removing the custom destructor the problem was solved. Hope that helps someone else.

**Comment by hemantthorat** [comment]
Anyway , I can't re-produce above issue because i have migrated code to something else.  This issue can be close for now. I will re-open it if i found it again.
Thanks

**Comment by michaelklishin** [comment]
Closing per @hemantthorat's comment. If @githoober's comment is still relevant, please open a new issue with a more specific title.
