### ISSUE TITLE
E_WARNING: array_push() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by fprochazka** [videlalvaro/php-amqplib#230]
https://github.com/videlalvaro/php-amqplib/blob/4d57fde8c3eb5b4a9577cef15ab874150c7655cb/PhpAmqpLib/Connection/AbstractConnection.php#L574

full trace:

```
   E_WARNING: array_push() expects parameter 1 to be array, null given
   
   in PhpAmqpLib/Connection/AbstractConnection.php(574) 
   in PhpAmqpLib/Connection/AbstractConnection.php(574) array_push()
   in PhpAmqpLib/Channel/AbstractChannel.php(190) PhpAmqpLib\Connection\AbstractConnection->wait_channel()
   in PhpAmqpLib/Channel/AbstractChannel.php(324) PhpAmqpLib\Channel\AbstractChannel->next_frame()
   in PhpAmqpLib/Connection/AbstractConnection.php(634) PhpAmqpLib\Channel\AbstractChannel->wait()
   in PhpAmqpLib/Connection/AbstractConnection.php(271) PhpAmqpLib\Connection\AbstractConnection->close()
   in PhpAmqpLib/Connection/AbstractConnection.php(260) PhpAmqpLib\Connection\AbstractConnection->safeClose()
   in [internal function]PhpAmqpLib\Connection\AbstractConnection->__destruct()
```

If you know what introduced this, can you point me at the right direction please? Otherwise I will bisect it later, when I have the time for it. I just wanned to report it for now.

**Comment by baruica** [comment]
I have got the same problem since I upgraded my Ubuntu box from 12.04/php 5.4 to 14.10/php 5.5

**Comment by laapsaap** [comment]
+1

**Comment by videlalvaro** [comment]
The problem seems to be related to this: https://github.com/videlalvaro/php-amqplib/blob/master/PhpAmqpLib/Channel/AMQPChannel.php#L123

During a connection close `channels` are tear-down'ed, being removed from $this->channels array from the connection object, therefore the `frame_queue` is null when accessed by `wait_channel`

**Comment by videlalvaro** [comment]
Perhaps a solution would be to null check before accessing a channel from `$this->channels` assuming said channel has been closed already.

**Comment by fprochazka** [comment]
@videlalvaro I "only" moved it https://github.com/videlalvaro/php-amqplib/commit/9226d61abb63f7d7e8d7094d2c30d510cfe2c9f8

**Comment by videlalvaro** [comment]
This should be fixed by https://github.com/videlalvaro/php-amqplib/commit/f4dd87a9e7398ed213bce6b56d77556e4f9378ab
