### ISSUE TITLE
Is the msg can not be 0

### ISSUE THREAD

**Issue by muyline** [videlalvaro/php-amqplib#239]
When i set the msg to be 0, the receiver can not receive the msg.And when the connection is closed, it throws exception like this.

PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolConnectionException' with message 'UNEXPECTED_FRAME - expected content body, got non content body frame instead' in /www/yemulin/rabbitmq_php/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:713

below is my code:
 1 <?php
  2 require_once __DIR__.'/vendor/autoload.php';
  3 use PhpAmqpLib\Connection\AMQPConnection;
  4 use PhpAmqpLib\Message\AMQPMessage;
  5 $connection = new AMQPConnection('localhost', 5672, 'guest', 'guest');
  6 $channel = $connection->channel();
  7 $channel->queue_declare('hello', false, false, false, false);
  8 $msg = new AMQPMessage(0);
  9 $channel->basic_publish($msg, '', 'hello');
 10 echo " [x] Send 'Hello World'\n";sleep(1);
 11 
 12 $channel->close();
 13 $connection->close();

**Comment by michaelklishin** [comment]
Message bodies must be strings. Please ask questions on rabbitmq-users.

**Comment by videlalvaro** [comment]
What @michaelklishin said. Closing
