### ISSUE TITLE
Out of memory on new connection with default RabbitMQ install

### ISSUE THREAD

**Issue by jampy** [videlalvaro/php-amqplib#240]
I'm trying to get startet with RabbitMQ and PHP.

So, I simpy installed RabbitMQ following the instructions on http://www.rabbitmq.com/install-debian.html in a Dabian 6 (Squeeze) installation. I did not change the configuration and `rabbitmqctl status` seems to work.

However, this simple code....

```php
<?php

spl_autoload_register(function($class) {
  $fn = "../../includes/" . str_replace("\\", "/", $class) . ".php";
  require_once $fn;
}, true);


//------------------------------------------------------------------------------

$connection = new \PhpAmqpLib\Connection\AMQPConnection('localhost', 5672, 'guest', 'guest');

?> 
```

...crashes with out-of-memory error:

```
$ php test.php
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1342243082 bytes) in /home/projpf/includes/PhpAmqpLib/Wire/IO/StreamIO.php on line 135
```

Frankly, I have no idea what's going on. Trying different user/passwords (which have not been configured) has no effect.

Any hints?

**Comment by videlalvaro** [comment]
Any reason why you aren't using the default autoloader from the library?

**Comment by jampy** [comment]
Because this will be integrated in a larger project that won't work with the default autoloader.

Why does that matter?

**Comment by videlalvaro** [comment]
Because the library is instantiating Objects all the time, to do so it needs to find the classes, so I wanted to rule out the case where there might be an issue with the autoloader used, so first I would use the default autoloader and see if the problem persists. If that's the case, then I would debug de connection objects.

Also, what version of the library are you using? Line 135 on master is a comment

**Comment by jampy** [comment]
Ok, here are the exact steps to reproduce:
1. installed current composer
2. downloaded [release 2.4.1](https://github.com/videlalvaro/php-amqplib/releases/tag/v2.4.1)
3. untared the source
4. executed `composer.phar install` in the php-amqplib directory to get the autoloader (it downloaded some additional packages)
5. run the following test script:

```
<?php
require_once "php-amqplib-2.4.1/vendor/autoload.php";
$connection = new \PhpAmqpLib\Connection\AMQPConnection('localhost', 5672, 'guest', 'guest');
?> 
```

Output:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1342243082 bytes) in /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Wire/IO/StreamIO.php on line 135
```

Same happens with current master (error happens at StreamIO.php:144 in that case).

This is using `PHP 5.4.10 (cli) with Zend Engine v2.4.0` (built from source).

FYI, when executing the same script with `PHP 5.3.3-7+squeeze15 with Suhosin-Patch` (standard Debian package) I get a different, but apparently related error:
```
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error reading data. Received 1 instead of expected 1342243081 bytes' in /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Wire/IO/StreamIO.php:152
Stack trace:
#0 /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Wire/AMQPReader.php(173): PhpAmqpLib\Wire\IO\StreamIO->read(1342243081)
#1 /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Wire/AMQPReader.php(128): PhpAmqpLib\Wire\AMQPReader->rawread(1342243081)
#2 /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Connection/AbstractConnection.php(564): PhpAmqpLib\Wire\AMQPReader->read(1342243081)
#3 /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Connection/AbstractConnection.php(596): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Channel/AbstractChannel.php(184): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 0)
#5 /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Chann in /home/projpf/_test/rabbit2/php-amqplib-2.4.1/PhpAmqpLib/Wire/IO/StreamIO.php on line 152
```

Maybe there is something wrong with the RabbitMQ installation, but (as said) I did nothing more than install the RabbitMQ Debian package.

**Comment by videlalvaro** [comment]
I would try to make sure the credentials are correct, for example, user,
password, port, vhost and so on. Specifically make sure that that in your
installation the guest user has access to the default vhost.

**Comment by jampy** [comment]
Solved: aptitude installed version 1.8.1-1 (latest Debian Squeeze version). I had to use `aptitude install rabbitmq-server/testing` (the `/testing` caused aptitude to use the RabbitMQ repository).

Now my test script does not throw any errors anymore (haven't done any other tests).

However, I'm astounded that this could cause such a fatal error in php-amqplib. I would expect it to be more robust, like recognizing an incompatible protocol or similar. I'm a bit concerned of using it in a large production system.

What are your thoughts?

**Comment by videlalvaro** [comment]
Me along others have used it in production systems for years, in small and
big websites. It has over 700k installs overall and over 80k installs in
the last month. See packagist for the stats. Still don't take my word on
it.

I also welcome pull requests for better error handling/and error messages

**Comment by jampy** [comment]
Well, thanks anyway.

**Comment by michaelklishin** [comment]
I have submitted #242 to make the README slightly clearer. @jampy while I agree that this should be handled better, this is the first time I see someone use a pre-1.8 version in a couple of years.

**Comment by jampy** [comment]
@michaelklishin: I installed a pre-2 version by accident (as described, because APT choose to use the standard Debian Squeeze repo, which has 1.8 installed).

It just surprises me that php-amqplib crashes with an OOM error just because the server is too old. After all, it also responds with a AMQP protocol.

I'm successfully using php-amqplib now. However, I still have a weird feeling about how php-amqplib might react when some day things go a little worse than normal (like, when RabbitMQ or the network has a problem or ... whatever). Having my worker processes eat up all the memory they can get in such a situation is... not optimal ... you know what I mean...? ;-)

**Comment by michaelklishin** [comment]
@jampy last pre-2.0 release of RabbitMQ happened almost 5 years ago. We provide our own apt repo with the most recent release. There really aren't many people running into this problem these days,
so this is not a priority.

Modern client versions implement AMQP 0-9-1, which RabbitMQ 1.8.x does not support. This library is open source software maintained by 1 person, often in his free time. If you want to make the library handle connections to unsupported servers better, feel free to submit a pull request.
