### ISSUE TITLE
RabbitMq Client Integration With Google App Engine (PHP) (Codeigniter)

### ISSUE THREAD

**Issue by SumeetGohil** [videlalvaro/php-amqplib#243]
I am running a php application using Codeigniter and successfully uploaded to Google App Engine & Running ..

I am facing issue while integrating RabbitMq client library, It's working fine on local system after deploying it's not!

And after using try..catch i found..

 PhpAmqpLib\Exception\AMQPRuntimeException Object ( [message:protected] => Error Connecting to server(0): [string:Exception:private] => [code:protected] => 0 [file:protected] => /base/data/home/apps/s~pge-2015/1.382317962180174380/website/application/third_party/PhpAmqpLib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php [line:protected] => 27 [trace:Exception:private] => Array ( [0] => Array ( [file] => /base/data/home/apps/s~pge-2015/1.382317962180174380/website/application/third_party/PhpAmqpLib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php [line] => 21 [function] => __construct [class] => PhpAmqpLib\Wire\IO\StreamIO [type] => -> [args] => Arra

What is solution..?

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users and provide relevant snippets of your code.

**Comment by SumeetGohil** [comment]
There were two GAE Application where i was deploying.

One was Paid App
Second was not..

This issue raised when i had deployed to unpaid app !!

Solved
