### ISSUE TITLE
Use interfaces and full docblocks

### ISSUE THREAD

**Issue by bartfeenstra** [videlalvaro/php-amqplib#251]
The current code base is closely coupled to specific implementation classes that do not implement generic interfaces or even extend base classes. This prevent proper type hinting which, combined with the lack of (detailed) parameter and return value type hints, causes debugging to be a major pain as the code does not explain itself and the lack of type hints prevents early failures.

Please adopt a focus on implementing interfaces, and on providing type hints and full docblocks for every method. This will improve testability, pluggability, coding speed and quality, and reduce debugging frustrations.

**Comment by videlalvaro** [comment]
Feel free to submit a PR with the proposed changes

**Comment by bartfeenstra** [comment]
I'm sorry it wasn't clear this issue is about a policy change. I know we can submit PRs, but that won't help much if the primary maintainers do not follow the same best practices. The reason I opened this issue is to explain the benefits and maybe hear about reasons why they haven't been followed yet; best practices are just that, they are not laws and there are always situations in which a particular best practice cannot be followed.

**Comment by videlalvaro** [comment]
This is quite an old project that when I took over maintenance didn't even
work under PHP 5.3 strict mode. We have been trying to improve it over
time, but even the minimum change takes time.

Even more, this is a very popular project, thousands of other projects
depend on it in production, so we can't go adding BC breaking changes just
to satisfy one style of programming or another.

In my particular case I've been worried more about performance; about
trying to conform to the AMQP spec; adding support for AMQP 0.9.1 (before
it only supported the old protocol version); making the classes testable
(some of them, before there were no tests); and so on. All that takes time.

Other users have done quite big refactorings; adding doc block comments for
most methods; moving the project to conform to PSR standards and so on.
This again takes time.

**Comment by bartfeenstra** [comment]
I saw that the project was very old and expected that to be the reason. Thank you for confirming your support for these improvements. I hope to be able to start submitting PRs soon.
