### ISSUE TITLE
Publishing several messages with headers only and no body leads to amqp error

### ISSUE THREAD

**Issue by ljolin** [videlalvaro/php-amqplib#256]
To ensure our php consumers are woken up regularly, we send control messages on each queue every 10 seconds. Before upgrading from 2.4, it used to work perfectly, but with the 2.5 release, it get this message on rabbitmq log
`
{amqp_error,unexpected_frame,
            "expected method frame, got non method frame instead",none}
`

No error is raised on the publisher side, all messages seem to be properly published, but only the first message is actually dispatched. 

I use the `AMQPSocketConnection` to publish the control messages, and an `AMQPStreamConnection::basic_consume` with to retrieve them. 

I just solved this by setting a dummy body content on the control message.

**Comment by videlalvaro** [comment]
Thanks, I would assume some silly typecasting issue with empty strings. I will look into it

**Comment by michaelklishin** [comment]
This looks like a genuine framing issue.

**Comment by videlalvaro** [comment]
I can't reproduce the issue, see: https://github.com/videlalvaro/php-amqplib/blob/master/tests/Functional/Bug256Test.php
