### ISSUE TITLE
Checking timeout and reconnecting

### ISSUE THREAD

**Issue by pushpesh4u** [videlalvaro/php-amqplib#257]
How do I check for timeouts and do a reconnect.

The StreamIO.php had the methods for this but they are not accessible publicly.

Is there any way to do that.

Thanks,

**Comment by ptte** [comment]
You can wrap your code in a try statement and catch the `Exception\AMQPTimeoutException`. That means your connection has timed out, and you can then do a reconnect.

**Comment by pushpesh4u** [comment]
Does that mean I have to do a `try/catch` for every statement? Either publishing/consuming.

**Comment by gr0g** [comment]
Hi, can you please add an example for this - thanks

**Comment by pushpesh4u** [comment]
I got it working with @ptte's suggestion above. Please close this.
