### ISSUE TITLE
Connection problem using php-amqplib

### ISSUE THREAD

**Issue by shinz90** [videlalvaro/php-amqplib#263]
When trying to access the rabbitmq from client side and it return 500 internal server error.
Here the error log. How to resolve the problem like this?

Error log :   
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\\Exception\\AMQPRuntimeException' with message 'Error Connecting to server(13): Permission denied ' in /var/www/html/mydir/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:27\nStack trace:\n#0 /var/www/html/mydir/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(21): PhpAmqpLib\\Wire\\IO\\StreamIO->__construct('ip adress', 15672, 3, 3, NULL)\n#1 /var/www/html/mydir/send.php(13): PhpAmqpLib\\Connection\\AMQPStreamConnection->__construct('ip address', 15672, 'guest', 'guest')\n#2 {main}\n  thrown in /var/www/html/mydir/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 27

**Comment by michaelklishin** [comment]
```
Error Connecting to server(13): Permission denied
```

I suspect that SELinux or similar blocks outgoing connections.

**Comment by shinz90** [comment]
@michaelklishin How to solve it? I was already configured httpd to add the port 15672. But the result still the same.

**Comment by videlalvaro** [comment]
You are trying to connect to RabbitMQ using HTTP port 15672, but RabbitMQ's AMQP port is 5672. Please change that in your code.
