### ISSUE TITLE
 Registering a consumer to a queue after publishing a message does not get any messages. 

### ISSUE THREAD

**Issue by pushpesh4u** [videlalvaro/php-amqplib#265]
Hello,

I am publishing messages from a single producer and have 3 consumers reading from the queue.

When I publish a lot of messages and the queue starts to fill,  I am starting a new consumer which reads from the same queue, but this new consumer does not get any message.

My topology is:

```

producer -> main_exchange ->exchange_mail->queue->consumers (initially 3)

```

I am using topic exchanges and using exchangeToExchange binding.

What could be the cause for this.

On the google group, I got this suggestion:

`All the messages in the queue may have been allocated to ( but not processed /acked by ) the old consumers...`

What does this mean and if it is indeed true, how do I change that to ensure I increase/decrease consumers as and when needed.

**Comment by michaelklishin** [comment]
@pushpesh4u see tutorial 2. All messages may be already delivered but unacknowledged. Newly added consumers should get delivery otherwise.

Consumers can also have priorities and messages can have TTL. Please post your code and RabbitMQ log files as it is not possible to suggest more otherwise.

**Comment by michaelklishin** [comment]
In fact, please keep the discussion on the list. No need to ask the same question in multiple places. This is a bug tracker, not a forum.

**Comment by pushpesh4u** [comment]
@michaelklishin My bad. Please remove it.

**Comment by videlalvaro** [comment]
@pushpesh4u closing the issue
