### ISSUE TITLE
Priority queue support

### ISSUE THREAD

**Issue by corentin-larose** [videlalvaro/php-amqplib#268]
Hi,

PHP version => 5.5.9
rabbitMq version => 3.5.1
php-amqplib version => v2.5.0

RabbitMq started to support priority queue support as of 3.5.0 (https://www.rabbitmq.com/priority.html).

Coming back to the RabbitMq's "Work queues" tutorial (https://www.rabbitmq.com/tutorials/tutorial-two-php.html) code to simplify case, I tried to pass ```['x-max-priority' => 2]``` argument as the 7th ```($arguments)``` argument of the ```queue_declare()``` function:

```php
$channel->queue_declare('task_queue', false, true, false, false, false, ['x-max-priority' => 2]);
```
I get the following exception:
```php
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPOutOfRangeException' with message 'AMQP-rabbit doesn't define data of type []' in /media/localhost/www.development.qapa.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPAbstractCollection.php:416
Stack trace:
#0 /media/localhost/www.development.qapa.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php(410): PhpAmqpLib\Wire\AMQPAbstractCollection::getDataTypeForSymbol(NULL)
#1 /media/localhost/www.development.qapa.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php(401): PhpAmqpLib\Wire\AMQPWriter->write_table(Array)
#2 /media/localhost/www.development.qapa.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(624): PhpAmqpLib\Helper\Protocol\Protocol091->queueDeclare(0, 'task_queue', false, true, false, false, false, Array)
#3 /media/localhost/www.development.qapa.com/public/test/worker.php(11): PhpAmqpLib\Channel\AMQPChannel->queue_declare('task_queue', false, true, false, false, false, Array)
#4 {main}
 in /media/localhost/www.development.qapa.com/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPAbstractCollection.php on line 416
```
Did I miss something?

Thanks!

**Comment by corentin-larose** [comment]
Ok, just found that I had to pass a hash in the type=> value format!

**Comment by jaconel** [comment]
@corentin-larose I receiving the same error while attempting to pass in a customer "version" header. Can you provide me with sample code of the structure in which these custom keys should be passed in?

**Comment by videlalvaro** [comment]
In the future, if what you are trying to do can be achieved by calling AMQP methods, like basic.consume and so on, this library should support those features in the broker. It's just a matter of providing the right arguments, like in this case

**Comment by bonndan** [comment]
For the record:

```
['x-max-priority' => ['I', 3600000]]
```

**Comment by aprilsacil** [comment]
@corentin-larose what do you mean by "hash in the [type, value] format!"?

**Comment by bonndan** [comment]
@corentin-larose see my comment

https://github.com/php-amqplib/php-amqplib/issues/268#issuecomment-153067421

**Comment by aprilsacil** [comment]
thank you @bonndan!!!

**Comment by janhapke** [comment]
For anybody who finds this on Google while searching for the error message:

Instead of doing this (and having to figure out what 'I' stands for and what other types there are)
```
['x-max-priority' => ['I', 3600000]]
```

You can also use
```
new AMQPTable(['x-max-priority' => 3600000])
```

**Comment by FractalizeR** [comment]
Why is `3600000` here? :) Is it some kind of magic number? I doubt someone needs such a high priority. BTW, as I know, having a big variety of priorities slows down RabbitMQ.

**Comment by michaelklishin** [comment]
Thanks, @FractalizeR. I edited the comment to use a more reasonable value. FYI, there is now a Resource Usage Considerations section in [RabbitMQ priority queue docs](http://www.rabbitmq.com/priority.html).

**Comment by FractalizeR** [comment]
@michaelklishin  Exactly! And they say:
> There is some in-memory and on-disk cost per priority level per queue. There is also an additional CPU cost, especially when consuming, so you may not wish to create huge numbers of levels.
