### ISSUE TITLE
AMQP Version 1.0

### ISSUE THREAD

**Issue by phpUser2015** [videlalvaro/php-amqplib#270]
Is there a plan to upgrade to AMQP Spec 1.0 so that the library could work with ActiveMQ and Apollo?

**Comment by michaelklishin** [comment]
AMQP 1.0 is a completely different protocol. No, there are no plans to do that. It should be a separate library.

**Comment by MPParsley** [comment]
@fullStackDev316, what library are you using to for ActiveMQ?
