### ISSUE TITLE
AMQPConnection.php marked as deprecated

### ISSUE THREAD

**Issue by Nguimjeu** [videlalvaro/php-amqplib#274]
I wanted to know why `AMQPConnection.php` in master branch is marked as deprecated.

**Comment by videlalvaro** [comment]
Because you should use AMQPStreamConnection, AMQPSocketConnection or the SSL one

**Comment by topikito** [comment]
Thanks @videlalvaro , I also experienced this confusion. Would be nice to update the example in the readme.md file. Not doing myself a pull request because I just started today with your library

**Comment by Nguimjeu** [comment]
Ok thanks! I understand now.
