### ISSUE TITLE
which version supports php 5.2 ?

### ISSUE THREAD

**Issue by jinleileiking** [videlalvaro/php-amqplib#279]

**Comment by videlalvaro** [comment]
Not sure any of them does, since when I took over maintenance of this library my goal was to make it work with PHP 5.3

**Comment by joaocc** [comment]
I was about to ask the same question, since we have a customer still on PHP 5.2.
If php-amqplib doesn't support it, do you know of any similar lib that does? 
Thx

**Comment by videlalvaro** [comment]
Take a look here: https://github.com/videlalvaro/php-amqplib/blob/master/NOTE.DEVELOPMENT.NOV.2011.md

**Comment by joaocc** [comment]
Thx
