### ISSUE TITLE
Class PhpAmqpLib\Wire\ not found

### ISSUE THREAD

**Issue by manti** [videlalvaro/php-amqplib#281]
Clas  PhpAmqpLib\Wire not available sometimes( not always ), Maybe cache problem. please suggest solutions for this 
<b>stack trace </b>: 
../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php (59)
../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php (57)
../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php (24)
../app/cache/prod/appProdProjectContainer.php (965)
../app/bootstrap.php.cache (2023)
../app/cache/prod/appProdProjectContainer.php (1153)
../app/bootstrap.php.cache (2023)
…www/ray-api/releases/20150610085811/app/cache/prod/appProdProjectContainer.php (1306)
../app/bootstrap.php.cache (2023)
../app/cache/prod/appProdProjectContainer.php (1164)
../app/bootstrap.php.cache (2023)
…r/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php (253)
/ApiBundle/Controller/....Controller.php (236)

**Comment by videlalvaro** [comment]
I honestly don't know on what kind of environment you are running.

**Comment by michaa76** [comment]
i think it's connected with https://github.com/videlalvaro/php-amqplib/issues/283
can u please check it out if the sollution attached works for u?

**Comment by manti** [comment]
@michaa76 thanks
