### ISSUE TITLE
Class 'PhpAmqpLib\Exception\AMQPIOException' not found in PhpAmqpLib/Wire/IO/StreamIO.php on line 161

### ISSUE THREAD

**Issue by michaa76** [videlalvaro/php-amqplib#283]
in multi process environment in one application of mine there is problem:
###
Fatal error: Class 'PhpAmqpLib\Exception\AMQPIOException' not found in /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 161
###
Call Stack:
    0.0005     221976   1. {main}() /home/vagrant/Projects/project-xyz/manager.php:0
    0.0922    1201216   2. X\Y\Z->run() /home/vagrant/Projects/project-xyz/manager.php:42
    1.3319    3374912   3. X\Y\Z->doStartProcess() /home/vagrant/Projects/project-xyz/src/X/Y/Z.php:60
    1.3882    3414832   4. X\Y\ZProcess->start() /home/vagrant/Projects/project-xyz/src/X/Y/Z.php:98
    1.3882    3414832   5. UnixProcess\AbstractUnix->start() /home/vagrant/Projects/project-xyz/src/X/Y/ZProcess.php:70
    1.7922    6778256   6. PhpAmqpLib\Connection\AbstractConnection->__destruct() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:0
    1.7922    6778328   7. PhpAmqpLib\Connection\AbstractConnection->safeClose() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:260
    1.7922    6778520   8. PhpAmqpLib\Connection\AbstractConnection->close() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:271
    1.7922    6779160   9. PhpAmqpLib\Connection\AbstractConnection->closeChannels() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:628
    1.7922    6779384  10. PhpAmqpLib\Channel\AMQPChannel->close() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:956
    1.7924    6780968  11. PhpAmqpLib\Channel\AbstractChannel->wait() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:174
    1.7924    6781112  12. PhpAmqpLib\Channel\AbstractChannel->next_frame() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:355
    1.7924    6781112  13. PhpAmqpLib\Connection\AbstractConnection->wait_channel() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:214
    1.7924    6781112  14. PhpAmqpLib\Connection\AbstractConnection->wait_frame() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:568
    1.7924    6781160  15. PhpAmqpLib\Wire\AMQPReader->read() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:528
    1.7924    6781160  16. PhpAmqpLib\Wire\AMQPReader->rawread() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:105
    1.7924    6781160  17. PhpAmqpLib\Wire\IO\StreamIO->read() /home/vagrant/Projects/project-xyz/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:147
###

Solution (to proof):
after changing in composer.json "autoload" from "psr-0" > "psr-4" there is no problem any more.

**Comment by videlalvaro** [comment]
can we close this issue?

**Comment by michaa76** [comment]
Hello
if it works for everybody, who reported it, then u can for sure close it.
Thanks a lot!
Am 23.06.2015 11:44 schrieb "Alvaro Videla" <notifications@github.com>:

**Comment by talent0yao** [comment]
I've also got this problem recently,may i ask how you resolve it?(my poor english...)
