### ISSUE TITLE
 Class 'AMQPTable' not found

### ISSUE THREAD

**Issue by gholol** [videlalvaro/php-amqplib#286]
What happened to it? what should i use now to set message headers?

**Comment by michaelklishin** [comment]
[Like so](https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_message_headers_snd.php#L21-47)?

**Comment by gholol** [comment]
Well this is clearly outdated. There's no Wire\AMQPTable class.

**Comment by michaelklishin** [comment]
[There is](https://github.com/videlalvaro/php-amqplib/blob/master/PhpAmqpLib/Wire/AMQPTable.php) in master.

**Comment by gholol** [comment]
Yeah, I just noticed it... not sure what it isn't available in my vendor folder through


http://i.imgur.com/NEYoaM5.png


 i'm using 2.4.* branch. I'll try with 2.4-dev


      "videlalvaro/php-amqplib": "2.4.*"

**Comment by gholol** [comment]
It's still not available after installing via composer, i had to clone this repository. Is there anything wrong with your package, or I'm using older version?

**Comment by videlalvaro** [comment]
I've just installed the library from packagist using `dev-master` and everything works as expected. Perhaps your issue is related to this? https://github.com/videlalvaro/php-amqplib/issues/283
