### ISSUE TITLE
queue_declare error

### ISSUE THREAD

**Issue by Jonas-Mui** [videlalvaro/php-amqplib#287]
error infomation:inequivalent arg 'x-message-ttl' for queue 'queue30mdelay' in vhost '/': received none but current is the value '1800000' of type 'long'"

my codes
$this->conn = new PhpAmqpLib\Connection\AMQPConnection($rabbitMqConfig['host'], $rabbitMqConfig['port'], $rabbitMqConfig['user'], $rabbitMqConfig['password']);

$this->ch = $this->conn->channel();
 if($argument != null){
                 $argument = new PhpAmqpLib\Wire\AMQPTable($argument);
              }
$this->ch->queue_declare($queue, false, true, false, false,$argument);

========================argument config===================
 'argument'=>array(
        "x-message-ttl" => 1800000,
        "x-max-length"=>5000000,
     "x-dead-letter-exchange"=>'jollychic.topic',
        "durable"=>true
       )

**Comment by michaelklishin** [comment]
You can't re-declare a queue with a different set of arguments. Delete it and declare it again. This is what the error message says:

```
inequivalent arg 'x-message-ttl' for queue 'queue30mdelay' in vhost '/': received none but current is the value '1800000' of type 'long'"
```
