### ISSUE TITLE
basic_qos() prefetch count ignored

### ISSUE THREAD

**Issue by gknapp** [videlalvaro/php-amqplib#297]
Hi,

In the [RabbitMQ tutorials](https://www.rabbitmq.com/tutorials/tutorial-two-php.html), it mentions prefetch count being set via the `basic_qos()` method (see Fair Dispatch section).

`basic_qos($prefetch_size, $prefetch_count, $global)`

I've changed the prefetch count argument and watched my script connect to RabbitMQ via the management console, it always reports a prefetch count of 1, even if I set this to something else.

If I change the prefetch size to anything other than NULL or 0, my scripts blows up with `Broken pipe or closed connection`

How do I change the prefetch count per channel using this library?

**Comment by videlalvaro** [comment]
Do you send the basic_qos before the basic_consume?

**Comment by gknapp** [comment]
Yes
```php
public function onNewMessage(callable $callback)
{
    $this->channel->basic_qos(null, 1, null);
    $this->channel->basic_consume(
        $this->name, '', false, false, false, false, $callback
    );
}
```

**Comment by gknapp** [comment]
I managed to get this working after some trial and error. I found I must set the following args on `basic_qos()`.

```php
$prefetchSize = null; // msg size in bytes, must be null else error
$prefetchCount = 1;
$applyPerChannel = null; // can be false or null, otherwise error

$channel->basic_qos($prefetchSize, $prefetchCount, $applyPerChannel);
$channel->basic_consume(...);
```

I'm able to change `$prefetchCount` to other values and it's respected.

**Comment by cernio** [comment]
Thanks!

2015-07-28 14:53 GMT+02:00 Greg Knapp <notifications@github.com>:

> I managed to get this working after some trial and error. I found I must
> set the following args on basic_qos().
>
> $prefetchSize = null; // msg size in bytes, must be null else error$prefetchCount = 1;$applyPerChannel = null; // can be false or null, otherwise error$channel->basic_qos($prefetchSize, $prefetchCount, $applyPerChannel);$channel->basic_consume(...);
>
> I'm able to change $prefetchCount to other values and it's respected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/videlalvaro/php-amqplib/issues/297#issuecomment-125593422>
> .
>



-- 

[image: Enrico Marongiu on about.me]

Enrico Marongiu
about.me/cernio
skype: cerionmorgauin
  <http://about.me/cernio>

**Comment by videlalvaro** [comment]
Sorry, I've been away. This worked for me: https://github.com/videlalvaro/php-amqplib/blob/master/demo/basic_qos.php#L12

**Comment by kgrosvenor** [comment]
Setting them as null seems to be a hack right??
