### ISSUE TITLE
Problem in $ch->queue_declare

### ISSUE THREAD

**Issue by cocoroco** [videlalvaro/php-amqplib#311]
hello, im new in amqp, them please if this is a simple question i apologize, but i have many hours and i cant solved this error, when i try to use the AMQPChannel, i have this line

$conn = new AMQPConnection(HOST, PORT, USER, PASS, VHOST);
$ch=$conn->channel();

$ch->queue_declare('task_queue', false, true, false, false);
.......
.....

when i open the web, i have this error

 Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolChannelException' with message 'ACCESS_REFUSED - access to queue 'task_queue' in vhost '/folder' 
refused for user 'myuser' in ......\videlalvaro\php-amqplib\PhpAmqpLib\Channel\AMQPChannel.php:191 
Stack trace: 
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel->channel_close(Object(PhpAmqpLib\Wire\AMQPReader)) 
#1 .....\vendor\videlalvaro\php-amqplib\PhpAmqpLib\Channel\AbstractChannel.php(194): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader)) 
#2 .....\vendor\videlalvaro\php-amqplib\PhpAmqpLib\Channel\AbstractChannel.php(393): PhpAmqpLib\Channel\AbstractChannel->dispatch('20,40', '\x01\x93fACCESS_REFUS...', NULL) 
#3 .....\vendor\videlalvaro\php-amqplib\PhpAmqpLib\Channel\AMQPChannel.php(634): PhpAmqpLib\Channel\AbstractChannel->wait(Array) 
#4 .....\amqp.php(15): PhpAmqpLib\Channel\AMQPChannel->queue_declare('task_queue', false, true, false, false) 
#5 {main} thrown in .....\vendor\videlalvaro\php-amqplib\PhpAmqpLib\Channel\AMQPChannel.php on line 191

but if delete the line : 

 $ch->queue_declare('task_queue', false, true, false, false);

i no have error

**Comment by videlalvaro** [comment]
The error message says:

>'ACCESS_REFUSED - access to queue 'task_queue' in vhost '/folder' 

Make sure the user you are connecting with can declare queues on the `/folder` vhost.

See: https://www.rabbitmq.com/access-control.html and https://www.rabbitmq.com/man/rabbitmqctl.1.man.html#Access%20control
