### ISSUE TITLE
Undefined class constant 'DELIVERY_MODE_PERSISTENT'

### ISSUE THREAD

**Issue by dizzu** [videlalvaro/php-amqplib#333]
What happened to AMQPMessage::DELIVERY_MODE_PERSISTENT constant? I had "videlalvaro/php-amqplib": "2.4.*@dev" in my composer.json and all worked ok, but now those constants are not there.

**Comment by videlalvaro** [comment]
This: https://github.com/videlalvaro/php-amqplib/blob/master/PhpAmqpLib/Message/AMQPMessage.php#L12 ?
