### ISSUE TITLE
Composer package is too heavy and can be reduce by 92%

### ISSUE THREAD

**Issue by laurentj** [videlalvaro/php-amqplib#335]
When we install the lib from Composer, it comes with many files that we don't care as a simple user.

Please add a .gitattributes file, containing the list of file to ignore when creating a composer package.

```
spec/  export-ignore
tests/  export-ignore
doc/  export-ignore
demo/  export-ignore
benchmark/  export-ignore
Makefile  export-ignore
NOTE.DEVELOPMENT.NOV.2011.md   export-ignore
NOTE.THENETCIRCLE.md export-ignore
phpunit.xml export-ignore
.travis.yml export-ignore
.editorconfig export-ignore
.gitignore export-ignore
```

With this .gitattributes file, the package is about 436KB. Without it, it costs 5,9MB. So each time a package is downloaded, we download useless files that represents 92% of the weight of the package ! With this .gitattributes, installing the package will be faster, lighter, and will save many bandwidth.

**Comment by videlalvaro** [comment]
Feel free to submit a PR

**Comment by laurentj** [comment]
Oups sorry, the master branch already contains a such file. I guess the next stable release will be a lightweight package :-)
