### ISSUE TITLE
I am trying to set priority queue but getting error PRECONDITION_FAILED

### ISSUE THREAD

**Issue by smudliyar** [videlalvaro/php-amqplib#344]
HI,
I am trying to set priority queue but getting following error

$ch->queue_declare($queue, false, true, false, false, false,['x-max-priority' => ['I', '10']]);

Getting following error:
Exception 'PhpAmqpLib\Exception\AMQPProtocolChannelException' with message 'PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'msgs' in vhost '/': received the value '10' of type 'signedint' but current is none'

So please help me out to find out where i am doing wrong?

**Comment by videlalvaro** [comment]
You probably had previously declared the queue without priorities and now you are trying to re-declare the same queue but with priorities.

AMQP doesn't allow this behaviour, so you'd have to delete the queue and re-declare it with priorities.
