### ISSUE TITLE
$Keepalive=true

### ISSUE THREAD

**Issue by hadoopmonica** [videlalvaro/php-amqplib#349]
My project is using your library to put messages to RabbitMQ, Thank you very much for your contribution, it makes my life much easier. My current problem is that the message speed is too fast and sometimes RabbitMQ stops working. In my current code is that when I need to publish a message I need to open and close connection. It gives too much overhead to RabbitMQ. 

If I need to use AMQPStreamConnection $keepalive = true, (I do not need to use SSL connection) , can you provide the sample code?

**Comment by postalservice14** [comment]
So you are closing the connection after every message?  You should be able to just:

1. Start PHP Code execution
2. Open the connection
3. Publish Messages N times
4. Close connection
5. End PHP Code execution

But maybe I'm misunderstanding something...

**Comment by hadoopmonica** [comment]
Thank you!
