### ISSUE TITLE
project really abandoned ?

### ISSUE THREAD

**Issue by mrbinr** [videlalvaro/php-amqplib#361]
Hi,
Sorry it's not really an issue, but when i've installed php-amqplib composer has display a warning 

> Package videlalvaro/php-amqplib is abandoned, you should avoid using it. No replacement was suggested.

Is this project really abandoned, or waiting for new mainteners ?
Can we still use it, or we have to find another package for managing RabbitMQ ?

Thanks
Best Regards,

Pascall

**Comment by videlalvaro** [comment]
Waiting for new maintainers, which I should grant commit access soon.

See https://github.com/videlalvaro/php-amqplib/issues/356
