### ISSUE TITLE
Reconsider non_blocking option of Channel::wait()

### ISSUE THREAD

**Issue by m00t** [videlalvaro/php-amqplib#67]
This option seems to be useless now, because actually blocking read is performed. Now with this option enabled wait() will return after something is received, not only when one of allowed methods is received. But if there is not data in the sockets, wait will not return ever even with this option enabled. IMO it is not an expected behaviour. 

This option is introdiced here: https://github.com/videlalvaro/php-amqplib/pull/11/files, but it is not even used in new non_blocking example. Seems like it is refuse from unsuccessful experiment

**Comment by JostBaron** [comment]
I'd really like to have the possibility to do a non-blocking `wait()`, since I'm reading messages from multiple channels (connected to multiple vhosts in rabbitmq, so it's not possible to combine them).

I'd use `stream_select` to find out if a channel changed, and then go through all channels checking for a new message.

So please, make this feature work!

**Comment by JostBaron** [comment]
I've found out how one can handle multiple connections at the same time:

        $sockets = [];
        foreach ($this->allAmqpChannels as $channel) {
            $sockets[] = $channel->getConnection()->getSocket();
        }

        echo "Number sockets: " . count($sockets) . "\n";

        while (true) {
            $readSockets = $sockets;
            $writeSockets = null;
            $exceptSockets = null;

            echo "Waiting for socket change...\n";

            if (false === ($numberChangedSockets = stream_select($readSockets, $writeSockets, $exceptSockets, null))) {
                echo "An error occurred while waiting for something to occurr on the queues.\n";
            } elseif ($numberChangedSockets > 0) {
                // Something arrived on a socket, check all channels for a new message.
                // Do so in a non-blocking way!
                foreach ($this->allAmqpChannels as $channel) {

                    if (in_array($channel->getConnection()->getSocket(), $readSockets, true)) {

                        // This is non-blocking, since there is data ready on the socket for this channel.
                        echo "\nGetting message\n";
                        $channel->wait();
                    }
                }
            }
        }
